/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package healthfocus;

import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kevin
 */
public class planesAlimenticiosFrame extends javax.swing.JFrame {
    consultasMysql consultas = new consultasMysql();
    encriptacion encript = new encriptacion();
    
    public static String nombre = "";
    public static String idUsuario, idPaciente;

    public static String getIdUsuario() {
        return idUsuario;
    }

    public static void setIdUsuario(String idUsuario) {
        planesAlimenticiosFrame.idUsuario = idUsuario;
    }

    public static String getIdPaciente() {
        return idPaciente;
    }

    public static void setIdPaciente(String idPaciente) {
        planesAlimenticiosFrame.idPaciente = idPaciente;
    }
    
    public static String getNombre() {
        return nombre;
    }

    public static void setNombre(String nombre) {
        planesAlimenticiosFrame.nombre = nombre;
    }
    
    /**
     * Creates new form planesAlimenticiosFrame
     */
    public planesAlimenticiosFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("ID Paciente");
        dtm.addColumn("Nombre");
        dtm.addColumn("Apellidos");
        dtm.addColumn("Sexo");
        dtm.addColumn("Fecha de nacimiento");
        dtm.addColumn("Fecha de consulta");
        this.tablapa.setModel(dtm);
        nuevaConsultaFrame ncf = new nuevaConsultaFrame();
        idUsuario = ncf.idUsuario;
        System.out.println("ID USUARIO: " + idUsuario);
        idPaciente = ncf.getNombre();
        System.out.println("ID PACIENTE: " + idPaciente);
        
        ResultSet resultado = consultas.cargarconsultas(idPaciente);
        String[] datos=new String[6];
        try {
            while(resultado.next()){
                datos[0]=encript.desEncriptar(resultado.getString(4));
                datos[1]=encript.desEncriptar(resultado.getString(5));
                datos[2]=encript.desEncriptar(resultado.getString(6));
                datos[3]=encript.desEncriptar(resultado.getString(7));
                dtm.addRow(datos);
            }
        } catch (SQLException ex) {
            Logger.getLogger(planesAlimenticiosFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablapa = new javax.swing.JTable();
        labelInfo = new javax.swing.JLabel();
        btnNuevaConsulta1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Historial de planes alimenticios");
        setMinimumSize(new java.awt.Dimension(1024, 720));
        setPreferredSize(new java.awt.Dimension(1024, 720));
        setSize(new java.awt.Dimension(1024, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablapa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablapa.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablapa.getTableHeader().setResizingAllowed(false);
        tablapa.getTableHeader().setReorderingAllowed(false);
        tablapa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablapaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablapa);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 47, 990, 268));

        labelInfo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 22)); // NOI18N
        labelInfo.setForeground(new java.awt.Color(153, 217, 234));
        labelInfo.setText("Historial de planes alimenticios");
        getContentPane().add(labelInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        btnNuevaConsulta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons_128px/plan.png"))); // NOI18N
        btnNuevaConsulta1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNuevaConsulta1.setBorderPainted(false);
        btnNuevaConsulta1.setContentAreaFilled(false);
        btnNuevaConsulta1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevaConsulta1.setFocusPainted(false);
        btnNuevaConsulta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaConsulta1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevaConsulta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel1.setText("Historiales de alimentación");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 550, -1, -1));

        labelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo_invertido_1024x720.png"))); // NOI18N
        getContentPane().add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablapaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablapaMouseClicked
        // TODO add your handling code here:
        int seleccion = tablapa.rowAtPoint(evt.getPoint());
        setNombre(String.valueOf(tablapa.getValueAt(seleccion, 0)));
        System.out.println(getNombre());

    }//GEN-LAST:event_tablapaMouseClicked

    private void btnNuevaConsulta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaConsulta1ActionPerformed
        // TODO add your handling code here:
        
        

        JFileChooser dlg = new JFileChooser();
        int option = dlg.showSaveDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            File f = dlg.getSelectedFile();
            f.toString();
            String ruta = f.toString();
            //String contenido = auxiliarAntedentes + auxiliarginecologico + auxiliarActividades + auxiliarDieta + auxiliarAntro;
            generarPDF g = new generarPDF();
            g.generarPDF("Health Focus", "", "Datos del nutriólogo", "C:\\Users\\Rafael\\Documents\\NetBeansProjects\\HealthFocus\\headerIcon.png", ruta + ".pdf");
        }
    }//GEN-LAST:event_btnNuevaConsulta1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(planesAlimenticiosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(planesAlimenticiosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(planesAlimenticiosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(planesAlimenticiosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new planesAlimenticiosFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevaConsulta1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelFondo;
    private javax.swing.JLabel labelInfo;
    private javax.swing.JTable tablapa;
    // End of variables declaration//GEN-END:variables
}
